config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :recipe_catogories, only: %i[index] do
    resources :recipes, only: %i[index show new create destroy] do
      resources :recipe_foods, only: %i[new create destroy update edit]
      resources :shopping_lists, only: %i[index]
    end
  end
  resources :users, only: [:create] do
    resources :foods, only: %i[index new create destroy]
  end

  get 'public', to: 'recipes#public', as: 'public'
  get 'index', to: 'users#index', as: 'index'
  put 'recipes/:id/update', to: 'recipes#update', as: 'update'
  put '/recipes/:id/recipe_foods/new', to: 'recipe_foods#new', as: 'new'

  root 'recipe_catogories#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, Recipe do |recipe|
        recipe.user_id == user.id || recipe.public
      end

      can [:update, :destroy], Recipe do |recipe|
        recipe.user_id == user.id
      end

      can :read, Food
      can :destroy, Food do |food|
        food.user_id == user.id
      end

      can %i[create], :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :recipe_catogory, class_name: 'RecipeCatogory'
  has_many :recipe_foods, dependent: :destroy

  def food_arr(recipe)
    food_arr = []
    recipe_foods = RecipeFood.where(recipe_id: recipe)
    recipe_foods.each do |recipe_food|
      Food.where(id: recipe_food.food_id).each do |food|
        food_arr.push(food)
      end
    end
    food_arr
  end

  def total_food_price(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @food_price_each = food.price * recipe_food.quantity
      end
      total += @food_price_each
    end
    total
  end

  def total_food_counts(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @food_count_each = recipe_food.quantity
      end
      total += @food_count_each
    end
    total
  end
end

app/models/recipe_catogory.rb
class RecipeCatogory < ApplicationRecord
  has_many :recipes
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role
  has_many :recipes, foreign_key: 'user_id'
  has_many :inventories, foreign_key: 'user_id'
  has_many :foods, foreign_key: 'user_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_role
    update(role: 'user')
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @categories = ['grams', 'milligrams', 'killograms', 'pound', 'ounce', 'litre', 'cup', 'teaspoon', 'spoon',
                   'fluid ounce']
  end

  def show
    @user = User.find(params[:user_id])
    @foods = Food.all
  end

  def create
    @food = Food.new(mass_params)
    @food.user_id = params[:user_id]

    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @user = User.find(params[:user_id])
    @food.destroy!
    @user.save
    redirect_to user_foods_path
    flash[:success] = 'food was deleted!'
  end

  private

  def mass_params
    params.require(:food).permit(:name, :unit, :price)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @category = RecipeCatogory.find(params[:recipe_catogory_id])
    @recipes = @category.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = Recipe.where(recipe_id: params[:recipe_id])
  end

  def new
    @recipe = Recipe.new
    @foods = Food.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:notice] = 'Recipe successfully created'
      redirect_to @recipe
    else
      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'The recipe was successfully destroyed.'
    redirect_to recipes_url
  end

  def public
    @public_recipes = Recipe.where(public: true)
    @public_recipe = Recipe.new
    @categories = RecipeCatogory.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(public: params[:public])
      flash[:success] = 'Recipe was successfully updated'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to recipe_catogory_recipe_path(@recipe, id: @recipe.id)
  end

  def own
    @recipes = Recipe.all
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cook_time, :prep_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventory_food_helper.rb
module InventoryFoodHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/recipe_catogories_helper.rb
module RecipeCatogoriesHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/index.html.erb
<div class="recipe-con">
  <div class="recipe-title">
  <h1><%= @category.name %> Recipes</h1>
  </div>
  <section class="recipe">
    <% @recipes.each do |recipe|%>
      <% if can? :read, recipe%>
        <div class="recipe-div" style="background-image: url(<%= recipe.img %>)">
          <div class="recipe-cont">
            <h1><%= recipe.name %></h1>
            <p><%= recipe.description %></p>
          </div>
          <div class="name-remove">
          <%= link_to "View Recipe", recipe_catogory_recipe_path(recipe, id: recipe.id), :class => "recipe-view-btn" %>
          </div>
          <%if can? :destroy, recipe%>
          <%= button_to 'Remove', recipe_catogory_recipe_path(recipe, id: recipe.id), method: :delete, class: 'delete'%>
          <%end%>
        </div>
      <% end %>
    <% end %>
  </section>
  <div class="wrap">
  <%= image_tag url_for('diet.png'), :class => "svg", :style => "height: 300px" %>
  <%= image_tag url_for('diet2.png'), :class => "svg", :style => "height: 200px" %>
  <%= image_tag url_for('food.png'), :class => "svg", :style => "height: 300px" %>
  <%= image_tag url_for('salad.png'), :class => "svg", :style => "height: 200px" %>
  <%= image_tag url_for('hot-pot.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('dish.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('hot.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('healthy-eating.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('food2.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('restaurant-cutlery-circular-symbol-of-a-spoon-and-a-fork-in-a-circle.png'), :class => "svg", :style => "height: 100px" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="new-recipe-form">
  <div class='food-con'>
    <p>Wecome <%=current_user.name%>, you can add a new recipe!</p>
  </div>
  <h1>New Recipe</h1>

  <%= form_with(model: @recipe, url: recipe_catogories_path) do |form| %>

  <%= form.text_field :name, placeholder: 'Name', class: 'form-inp'%>

  <%= form.number_field :cook_time, placeholder: 'Cooking time(In Minutes)', class: 'form-inp', min: '0' %>

  <%= form.number_field :prep_time, placeholder: 'Preparation time(In Minutes)', class: 'form-inp', min:'0'%>

  <%= form.text_area :description, placeholder: 'Description', class: 'form-inp' %>

  <div class="form-check form-switch">
    <%= form.check_box :public, class:"form-check-input", id:"flexSwitchCheckDefault"%>
    <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
  </div>
  <br>

  <div class='food-con'>
    <%= form.submit :Submit , class: "add-button" %>
  </div>

  <% end %>
</div>

app/views/recipes/own.html.erb
<section class="recipe">
    <% @recipes.each do |recipe|%>
    <% if can? :read, recipe%>
        <div class="recipe-div">
            <div class="recipe-cont">
                <div class="name-remove">
                <%= link_to "#{recipe.name}", recipe_catogory_recipe_path(recipe, id: recipe.id)%>
                <%if can? :destroy, recipe%>
                <%= button_to 'Remove', recipe_catogory_recipe_path(recipe, id: recipe.id), method: :delete, class: 'delete'%>
                <%end%>
                </div>
                <p><%= recipe.description %></p>
            </div>
        </div>
    <%end%>
    <% end %>
</section>

app/views/recipes/public.html.erb
<div id="category-container">
  <% @categories.includes(:recipes).each do |category| %>
  <h1><%= category.name %></h1>
  <%= image_tag url_for(category.image_url), :class => "cat-img" %>
  <p><%= category.description %></p>
  <section class="recipe">
    <%category.recipes.each do |recipe|%>
      <div class="recipe-div">
        <div class="recipe-cont">
          <%= image_tag url_for(recipe.img), :class => "rep-img" %>
          <div class="name-remove">
          <%= link_to "#{recipe.name}", recipe_path(recipe)%>
          <p><%=recipe.description %></p>
          <div class="recipe-prep-time">
          <p><%=recipe.prep_time %></p>
          <p><%= recipe.cook_time %></p>
          </div>
          </div>
        </div>
      </div>
    <% end %>
  </section>
  <% end %>
</div>

app/views/recipes/show.html.erb
<section class="recipe-show">
  <h1><%= @recipe.name %></h1>

  <% if can? :update, @recipe%>
  <div class="status">
    <%= form_with url: update_path(@recipe), method: "put" do |form| %>
    <div class="form-check form-switch">
      <% if @recipe.public == false %>
      <%= form.check_box :public, class:"form-check-input", id:"flexSwitchCheckDefault",role: "switch", onchange: "this.form.submit();"%>
      <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
      <% else %>
      <%= form.check_box :public, class:"form-check-input", id:"flexSwitchCheckChecked",role: "switch", checked: true, onchange: "this.form.submit();" %>
      <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>
      <%end%>

    </div>
    <%end%>
  </div>
  <%end%>

  <div class="recipe-details">
    <%= image_tag url_for(@recipe.img), :class => "r-img" %>
    <div class="recipe-details-cont">
    <p class=""><%=@recipe.description%></p>

    <p>Preparation time: <strong><%=@recipe.prep_time%></strong></p>

    <p>Cooking time: <strong><%=@recipe.cook_time%></strong></p>
    </div>
  </div>

  <h2>Instructions</h2>
  
  <section class="recipe-instructions">
  <% @recipe.instructions.each_with_index do |instruction, index| %>
  <div class="i-con">
  <div class="instruction">
    <p class="instruction-number"><%= index + 1 %></p>
    <p class="instruction-text"><%= instruction %></p>
  </div>
  </div>
  <% end %>
  </section>

  <hr>

  <%= render 'recipe_foods/recipe_food' %>

  <div class="wrap">
  <%= image_tag url_for('diet.png'), :class => "svg", :style => "height: 300px" %>
  <%= image_tag url_for('diet2.png'), :class => "svg", :style => "height: 200px" %>
  <%= image_tag url_for('food.png'), :class => "svg", :style => "height: 300px" %>
  <%= image_tag url_for('salad.png'), :class => "svg", :style => "height: 200px" %>
  <%= image_tag url_for('hot-pot.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('dish.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('hot.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('healthy-eating.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('food2.png'), :class => "svg", :style => "height: 100px" %>
  <%= image_tag url_for('restaurant-cutlery-circular-symbol-of-a-spoon-and-a-fork-in-a-circle.png'), :class => "svg", :style => "height: 100px" %>
  </div>
</section>

app/views/users/index.html.erb
<section class="about-container">
<h1>About the Application</h1>
<p>The Recipe app keeps track of all your recipes, ingredients, and inventory. It will allow you to save ingredients, keep track of what you have, create recipes, and generate a shopping list based on what you have and what you are missing from a recipe. Also, since sharing recipes is an important part of cooking the app should allow you to make them public so anyone can access them.</p>
<%= image_tag url_for('cooking.png'), :class => "logo-2" %>
<div class="foot">
Designed and developed by: <a href="https://github.com/hamid-murambiwa">Hamid Murambiwa</a> and <a href="https://github.com/adamteddychang">You-Wei (Adam) Chang</a>  © copyright 2022
</div>
</section>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>