config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :recipe_catogories, only: %i[index] do
    resources :recipes, only: %i[index show new create destroy] do
      resources :recipe_foods, only: %i[new create destroy update edit]
      resources :shopping_lists, only: %i[index]
    end
  end
  resources :users, only: [:create] do
    resources :foods, only: %i[index new create destroy]
  end

  get 'public', to: 'recipes#public', as: 'public'
  get 'index', to: 'users#index', as: 'index'
  put 'recipes/:id/update', to: 'recipes#update', as: 'update'
  put '/recipes/:id/recipe_foods/new', to: 'recipe_foods#new', as: 'new'

  root 'recipe_catogories#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, Recipe do |recipe|
        recipe.user_id == user.id || recipe.public
      end

      can [:update, :destroy], Recipe do |recipe|
        recipe.user_id == user.id
      end

      can :read, Food
      can :destroy, Food do |food|
        food.user_id == user.id
      end

      can %i[create], :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :recipe_catogory, class_name: 'RecipeCatogory'
  has_many :recipe_foods, dependent: :destroy

  def food_arr(recipe)
    food_arr = []
    recipe_foods = RecipeFood.where(recipe_id: recipe)
    recipe_foods.each do |recipe_food|
      Food.where(id: recipe_food.food_id).each do |food|
        food_arr.push(food)
      end
    end
    food_arr
  end

  def total_food_price(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @food_price_each = food.price * recipe_food.quantity
      end
      total += @food_price_each
    end
    total
  end

  def total_food_counts(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @food_count_each = recipe_food.quantity
      end
      total += @food_count_each
    end
    total
  end
end

app/models/recipe_catogory.rb
class RecipeCatogory < ApplicationRecord
  has_many :recipes
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role
  has_many :recipes, foreign_key: 'user_id'
  has_many :inventories, foreign_key: 'user_id'
  has_many :foods, foreign_key: 'user_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_role
    update(role: 'user')
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @categories = ['grams', 'milligrams', 'killograms', 'pound', 'ounce', 'litre', 'cup', 'teaspoon', 'spoon',
                   'fluid ounce']
  end

  def show
    @user = User.find(params[:user_id])
    @foods = Food.all
  end

  def create
    @food = Food.new(mass_params)
    @food.user_id = params[:user_id]

    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @user = User.find(params[:user_id])
    @food.destroy!
    @user.save
    redirect_to user_foods_path
    flash[:success] = 'food was deleted!'
  end

  private

  def mass_params
    params.require(:food).permit(:name, :unit, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_foods_params)
    if @recipe_food.save
      flash[:notice] = 'Food created successfully.'
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_foods_params)
      flash[:success] = 'Recipe Food updated successfully.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @category = RecipeCatogory.find(params[:recipe_catogory_id])
    @recipes = @category.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = Recipe.where(recipe_id: params[:recipe_id])
  end

  def new
    @recipe = Recipe.new
    @foods = Food.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:notice] = 'Recipe successfully created'
      redirect_to @recipe
    else
      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'The recipe was successfully destroyed.'
    redirect_to recipes_url
  end

  def public
    @public_recipes = Recipe.where(public: true)
    @public_recipe = Recipe.new
    @categories = RecipeCatogory.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(public: params[:public])
      flash[:success] = 'Recipe was successfully updated'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to recipe_catogory_recipe_path(@recipe, id: @recipe.id)
  end

  def own
    @recipes = Recipe.all
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cook_time, :prep_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventory_food_helper.rb
module InventoryFoodHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipe_foods/_recipe_food.html.erb
<section class='app-con'>
  <h2>Ingredients</h2>

  <div class="show-btns">
    <%= link_to 'Generate Shopping List',  recipe_catogory_recipe_shopping_lists_path(@recipe, recipe_id: @recipe.id), class: 'add-button' %>
    <% if can? :update, @recipe%>

    <%= link_to 'Add ingredient', new_recipe_catogory_recipe_recipe_food_path(@recipe, recipe_id: @recipe.id), class: 'add-button' %>

    <%end %>
  </div>
  <div>
    <table>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
      </tr>
      <% @recipe.recipe_foods.each do |rf| %>
      <tr>
        <td><%= rf.food.name %></td>
        <td><%= rf.quantity %><%= rf.food.unit  %></td>
        <td>R<%= rf.quantity * rf.food.price %></td>
        <td class="action-btns-td">
        <div class='ingr-btns'>
        <%if can? :update, @recipe%>
          <%=link_to "Update", edit_recipe_catogory_recipe_recipe_food_path(recipe_id: @recipe.id, id: rf.id), class:"add-button ingr-btn"%>
      <%end%>
      <%if can? :destroy, @recipe %>
          <%=button_to "Delete", recipe_catogory_recipe_path(recipe_id: @recipe.id, id: rf.id), method: :delete, class:"delete ingr-btn"%>
          <%end%>
          </div>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</section>

app/views/recipe_foods/edit.html.erb
<section class='app-con'>
  <div class='content-con'>
    <h2>Edit Ingredient</h2>

    <%= form_with model: @recipe_food, url: { action: "update"}, data: { turbo: false } do |f| %>
    <div class="field">
      <%= f.label :food %><br />
      <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"" %><br>
    </div>

    <div class="field">

      <%= f.label :quantity, class:"form-label" %><br>
      <%= f.number_field :quantity ,  class:"" , required: true, placeholder: 'quantity',  min: 1%><br>
    </div>



    <div class="actions">
      <%= f.submit "Update Ingredients" %>
    </div>
    <% end %>
  </div>
</section>

app/views/recipe_foods/new.html.erb
<section class='app-con'>
  <div class='content-con'>
    <h2>Add Ingredient</h2>

    <%= form_with model: [@recipe, @recipe.recipe_foods.create], data: { turbo: false } do |f| %>
    <div class="field">
      <%= f.label :food %><br />
      <%= f.collection_select :food_id, Food.all, :id, :name, prompt:true%><br>
    </div>

    <div class="field">

      <%= f.label :quantity, class:"form-label" %><br>
      <%= f.number_field :quantity ,  class:"" , required: true, placeholder: 'quantity',  min: 1%><br>
    </div>



    <div class="actions">
      <%= f.submit "Create Recipe Food" %>
    </div>
    <% end %>
  </div>
</section>