config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :recipe_catogories, only: %i[index] do
    resources :recipes, only: %i[index show new create destroy] do
      resources :recipe_foods, only: %i[new create destroy update edit]
      resources :shopping_lists, only: %i[index]
    end
  end
  resources :users, only: [:create] do
    resources :foods, only: %i[index new create destroy]
  end

  get 'public', to: 'recipes#public', as: 'public'
  get 'index', to: 'users#index', as: 'index'
  put 'recipes/:id/update', to: 'recipes#update', as: 'update'
  put '/recipes/:id/recipe_foods/new', to: 'recipe_foods#new', as: 'new'

  root 'recipe_catogories#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, Recipe do |recipe|
        recipe.user_id == user.id || recipe.public
      end

      can [:update, :destroy], Recipe do |recipe|
        recipe.user_id == user.id
      end

      can :read, Food
      can :destroy, Food do |food|
        food.user_id == user.id
      end

      can %i[create], :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :recipe_catogory, class_name: 'RecipeCatogory'
  has_many :recipe_foods, dependent: :destroy

  def food_arr(recipe)
    food_arr = []
    recipe_foods = RecipeFood.where(recipe_id: recipe)
    recipe_foods.each do |recipe_food|
      Food.where(id: recipe_food.food_id).each do |food|
        food_arr.push(food)
      end
    end
    food_arr
  end

  def total_food_price(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @food_price_each = food.price * recipe_food.quantity
      end
      total += @food_price_each
    end
    total
  end

  def total_food_counts(food_arr, _recipe_id)
    total = 0
    food_arr.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @food_count_each = recipe_food.quantity
      end
      total += @food_count_each
    end
    total
  end
end

app/models/recipe_catogory.rb
class RecipeCatogory < ApplicationRecord
  has_many :recipes
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role
  has_many :recipes, foreign_key: 'user_id'
  has_many :inventories, foreign_key: 'user_id'
  has_many :foods, foreign_key: 'user_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def set_role
    update(role: 'user')
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @categories = ['grams', 'milligrams', 'killograms', 'pound', 'ounce', 'litre', 'cup', 'teaspoon', 'spoon',
                   'fluid ounce']
  end

  def show
    @user = User.find(params[:user_id])
    @foods = Food.all
  end

  def create
    @food = Food.new(mass_params)
    @food.user_id = params[:user_id]

    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @user = User.find(params[:user_id])
    @food.destroy!
    @user.save
    redirect_to user_foods_path
    flash[:success] = 'food was deleted!'
  end

  private

  def mass_params
    params.require(:food).permit(:name, :unit, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventory_food_helper.rb
module InventoryFoodHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div id="desktop-header">
  <nav class="navbar">
  <nav class="navbar navbar-expand-lg navbar-light" id="desktop-header">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li>
            <%= link_to recipe_catogories_path do %>
              <%= image_tag "cooking.png", style: 'height:4vw;width:4vw;' %>
            <% end %>
          </li>

          <li class="list">
            <div class="btn-group dropend">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Meal Catagories
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Breakfast', recipe_catogory_recipes_path(recipe_catogory_id: 1), class: "dropdown-item" %></li>
                <li><%= link_to 'Lunch', recipe_catogory_recipes_path(recipe_catogory_id: 2), class: "dropdown-item" %></li>
                <li><%= link_to 'Dinner', recipe_catogory_recipes_path(recipe_catogory_id: 3), class: "dropdown-item" %></li>
                <li><%= link_to 'Snacks', recipe_catogory_recipes_path(recipe_catogory_id: 4), class: "dropdown-item" %></li>
                <li><%= link_to 'Dessert', recipe_catogory_recipes_path(recipe_catogory_id: 5), class: "dropdown-item" %></li>
                <li><%= link_to 'Drinks', recipe_catogory_recipes_path(recipe_catogory_id: 6), class: "dropdown-item" %></li>
                <li><%= link_to 'Other', recipe_catogory_recipes_path(recipe_catogory_id: 7), class: "dropdown-item" %></li>
              </ul>
            </div>
          </li>

          <li class="list">
            <div class="btn-group dropend">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
             Account Settings
            </button>
            <ul class="dropdown-menu">
              <li>
              <%= link_to 'Edit Account', edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <% if user_signed_in? %> 
              <li>
              <%= link_to 'Logout', '/users/sign_out', class: "dropdown-item" %>
              </li>
              <% else %>
              <li>
              <%= link_to 'Sign up', ' /users/sign_up', class: "dropdown-item" %>
              </li>
              <li>
              <%= link_to 'Login', '/users/sign_in', class: "dropdown-item" %>
              </li>
              <% end %>
            </ul>
            </div>
          </li>

          <li class="nav-item">
          <%= link_to 'About', index_path, class: "nav-link" %>
        </li>

        </ul>
      </div>
    </div>
  </nav>
  </nav>
  </div>

  <div id="mobile-header">
  <%= link_to recipe_catogories_path do %>
    <%= image_tag "cooking.png", style: 'height:5vw;width:5vw;', :class => 'logo' %>
  <% end %>
  <div class="collapse" id="navbarToggleExternalContent">
  <div>
    <h5 class="text-white h4"><%= link_to 'Edit Account', edit_user_registration_path, class: "dropdown-item" %></h5>
    <h5 class="text-white h4"><%= link_to 'Logout', '/users/sign_out', class: "dropdown-item" %></h5>
    <h5 class="text-white h4"><%= link_to 'About', index_path, class: "nav-link" %></h5>
    <p>
    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Meal Catagories
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
    <ul>
    <li><%= link_to 'Breakfast', recipe_catogory_recipes_path(recipe_catogory_id: 1), class: "dropdown-item" %></li>
    <li><%= link_to 'Lunch', recipe_catogory_recipes_path(recipe_catogory_id: 2), class: "dropdown-item" %></li>
    <li><%= link_to 'Dinner', recipe_catogory_recipes_path(recipe_catogory_id: 3), class: "dropdown-item" %></li>
    <li><%= link_to 'Snacks', recipe_catogory_recipes_path(recipe_catogory_id: 4), class: "dropdown-item" %></li>
    <li><%= link_to 'Dessert', recipe_catogory_recipes_path(recipe_catogory_id: 5), class: "dropdown-item" %></li>
    <li><%= link_to 'Drinks', recipe_catogory_recipes_path(recipe_catogory_id: 6), class: "dropdown-item" %></li>
    <li><%= link_to 'Other', recipe_catogory_recipes_path(recipe_catogory_id: 7), class: "dropdown-item" %></li>
  </ul>
    </div>
  </div>
  </div>
</div>
<nav class="navbar navbar-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta property="og:description" content="The Recipe app keeps track of all your recipes, ingredients, and inventory. It will allow you to save ingredients, keep track of what you have, create recipes, and generate a shopping list based on what you have and what you are missing from a recipe. Also, since sharing recipes is an important part of cooking the app should allow you to make them public so anyone can access them.">
    <meta property="og:image" content="https://user-images.githubusercontent.com/71644515/169563249-239f2c2b-89f4-402a-b849-2141fb768766.png" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'cooking.png' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Macondo&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>